### ISSUE TITLE
Description under title

### ISSUE THREAD

**Issue by lfarah** [vhesener/Closures#20]
<img width="408" alt="screen shot 2017-10-07 at 2 30 09 pm" src="https://user-images.githubusercontent.com/6511079/31307840-0fda7b26-ab6c-11e7-85dc-75622d3b3cd3.png">

Please fix this before we can approve [your PR on AwesomeiOS](https://github.com/vsouza/awesome-ios/pull/1993)

**Comment by dusty-commits** [comment]
![screen shot 2017-10-07 at 1 13 39 pm](https://user-images.githubusercontent.com/1163766/31310654-78c36c02-ab61-11e7-8016-1880af80aa77.png)

Complete. Thank you.
