### ISSUE TITLE
Dependency "Closures" has no shared framework schemes

### ISSUE THREAD

**Issue by mylesbarros** [vhesener/Closures#21]
When attempting to build Closures using Carthage I receive the error

`Dependency "Closures" has no shared framework schemes`

I haven't developed a framework before but it seems that that would also preclude Closures from supporting building for specific platforms (e.g., `carthage update --platform iOS`)

**Comment by dusty-commits** [comment]
Thank you for the find. Fixed in #22

**Comment by mylesbarros** [comment]
Great, thanks for the fix!
