### ISSUE TITLE
Use of unresolved identifier 'dismissFromPresenting'

### ISSUE THREAD

**Issue by NuGelaLiees** [vhesener/Closures#33]
when I clone it from cocoapod , xcode throw me this error ,when i want to use it on my project.  "UIImagePickerController.swift" extension init function "didCancel: @escaping ( _ picker: UIImagePickerController) ...."

**Comment by dusty-commits** [comment]
I've just run a test project with cocoapods and don't see this. Can you help me reproduce this?

**Comment by atmamont** [comment]
Set swift 4.0 for this pod target in build settings

**Comment by dusty-commits** [comment]
@NuGelaLiees , like @atmamont said, the Swift Language Version must be set to 4.0. 

If your project is set to Swift 3 or below, CocoaPods will automatically create the Pod with the same version (i.e. 3.2, the same as your project). `Closures` only supports Swift 4 and up.

If your project is Swift 4, simply go to the Pod project, select the Closures target, and change the Build Setting named "Swift Language Version" to 4.0.
