### ISSUE TITLE
button 的点击事件不行

### ISSUE THREAD

**Issue by boai** [vhesener/Closures#35]
![34afedd9-a5f2-4d04-a30e-575e96dc4170](https://user-images.githubusercontent.com/13014692/34751464-bc9900ba-f5e7-11e7-9c0e-d724218308cf.png)

swift 4.0，Xcode 9.2

**Comment by dusty-commits** [comment]
You have a linking problem somewhere. Have you imported the framework into your file? Have you [installed the framework](https://github.com/vhesener/Closures#installation)? Without much context, I'm not exactly sure how to help you.
