### ISSUE TITLE
UIImagePickerController: Use of unresolved identifier 'dismissFromPresenting'

### ISSUE THREAD

**Issue by sonswift** [vhesener/Closures#44]
Hello Vhesener,

I have a problem with Closers lib, my project is using Swift 3.3 and XCode 9.3.1. After installing Closers 0.4, I got issue like this 

<img width="793" alt="screen shot 2018-05-28 at 3 40 19 pm" src="https://user-images.githubusercontent.com/4739616/40605713-76868ca6-628d-11e8-86da-4115207c7fa9.png">

I'm not sure but it worked after changing `dismissFromPresenting` to `UIImagePickerController.dismissFromPresenting`

Please review it.

Thanks,
Son Thai.

**Comment by dusty-commits** [comment]
`Closures` only supports Swift 4.x+
